# Generated by Django 6.1 on 2026-08-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_delete_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanetDiscovery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planet_name', models.CharField(max_length=100)),
                ('galaxy', models.CharField(max_length=100)),
                ('star_system', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('discovery_date', models.DateTimeField(auto_now=True)),
                ('cover_image', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('planet_class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.planetclass')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
    ]
