# Generated by Django 6.1 on 2026-08-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_planetclass_role_planetdiscovery_account_role_id'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planetdiscovery',
            name='planet_class_id',
        ),
        migrations.RemoveField(
            model_name='planetdiscovery',
            name='account_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.role'),
        ),
        migrations.DeleteModel(
            name='PlanetClass',
        ),
        migrations.DeleteModel(
            name='PlanetDiscovery',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
