# Generated by Django 6.1 on 2026-08-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_planetdiscovery_planet_class_id_and_more'),
        ('planetclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetDiscovery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planet_name', models.CharField(max_length=100)),
                ('galaxy', models.CharField(max_length=100)),
                ('star_system', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('discovery_date', models.DateTimeField(auto_now=True)),
                ('cover_image', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('planet_class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planetclass.planetclass')),
            ],
        ),
    ]
